name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.10.4
            otp: 21.3.8.24
          - elixir: 1.11.4
            otp: 23.2
          - elixir: 1.12.3
            otp: 24.1
          - elixir: 1.13.0
            otp: 24.1
            check_formatted: true
            warnings_as_errors: true
          - elixir: 1.14.0
            otp: 25.0
            check_formatted: true
            warnings_as_errors: true

    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix format --check-formatted
        if: matrix.check_formatted
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - name: Compile test projects
        run: |
          cd test/projects/empty && mix deps.get && mix compile
          cd ../full && mix deps.get && mix compile
          cd ../initable && mix deps.get && mix compile
          cd ../missing_template && mix deps.get && mix compile
          cd ../missing_template_dir && mix deps.get && mix compile
      - run: mix compile --warnings-as-errors
        if: matrix.warnings_as_errors
      - run: mix test
